server:
  port: 8082

spring:
  application:
    name: BOOK-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB:localhost}:5432/postgres
    username: postgres
    password: password12
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: off
    org:
      springframework: error
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    console: '%msg%n'